### ISSUE TITLE
ImportError: No module named ais_swig

### ISSUE THREAD

**Issue by eythian** [bistromath/gr-ais#10]
When I run this:

```
$ ais_rx -dosmocom -g35 -r250e3 > ais_pipe
```

I get this:

```
Traceback (most recent call last):
  File "/usr/local/bin/ais_rx", line 7, in <module>
    import ais
  File "/usr/local/lib/python2.7/dist-packages/ais/__init__.py", line 45, in <module>
    from ais_swig import *
ImportError: No module named ais_swig
```

I didn't find any swig libraries in /usr/local/lib. If it'll make a difference, I'm using the commit `1813242` so that it'll work with gnuradio 3.7.5.

**Comment by linville** [comment]
In case anyone runs across this years later with the same problem, this is probably because swig not found during the cmake step and isn't being fully disabled.

When you run cmake, did you see this?
```
-- Checking for module SWIG
-- Disabling SWIG because version check failed.
```

Install swig using apt-get, pkg_add or whatever swig and re-run the cmake:
```
-- Checking for module SWIG
-- Found SWIG version 3.0.8.
-- Found SWIG: /usr/bin/swig3.0
```
