### ISSUE TITLE
Update Install

### ISSUE THREAD

**Issue by kylecavs** [bistromath/gr-ais#11]
Hi,
I would like to implement an AIS receiver using my USRP B210 with your software platform. However, when I clone gr-ais, make a build directory, and build gr-ais, there are missing blocks in GnuRadio-Companion. Can you please provide install instructions as well as procedure to run? I am running with Gnuradio 3.7.7.1.

Thanks,
Kyle

**Comment by bistromath** [comment]
gr-ais does not currently use gnuradio-companion. after installation, run
ais_rx to execute gr-ais.

--n

**Comment by ReverseControl** [comment]
@bistromath Has this changed? Are there gnu-radio companion blocks now? I installed it some weeks ago and did not see it. Incidentally, I cannot install it now. cmake finds errors.

**Comment by bistromath** [comment]
Which version of Gnuradio are you compiling it against?

I'll do a 3.9 port along with gr-air-modes as soon as this round of work is
done.

**Comment by ReverseControl** [comment]
I tried both 3.7 and 3.8, i got it to "build and install" for one of them but nothing showed up on the gnuradio-companion GUI. I now realized it was not meant to. 

The error happen as follows:

1. I installed in a docker container 20.04 LTS ubuntu: `pybombs prefix init  /root/gnuradio -a gnuradio -R gnuradio-default`
2. If you go here, https://github.com/gnuradio/pybombs, it says that should install gnuradio 3.8.
3. But, I get the following error when running `cmake ..` from <gr-ais parent folder>/build:
```
CMake Error at CMakeLists.txt:71 (find_package):
  Could not find a configuration file for package "Gnuradio" that is
  compatible with requested version "3.8".

  The following configuration files were considered but not accepted:

    /root/gnuradio/lib/cmake/gnuradio/GnuradioConfig.cmake, version: 3.7.14.0



-- Configuring incomplete, errors occurred!
See also "/root/gr-ais/build/CMakeFiles/CMakeOutput.log".
```

How long will it be until gr-ais is available in the gnuradio-companion GUI with version 3.9 of gnuradio?

**Comment by bistromath** [comment]
I've updated gr-ais (on the "grc" branch for now) to include GRC blocks and a GRC top-level application. Please note that it will only work with a version of Gnuradio which includes fixes to the MSK timing error detector -- see gnuradio/gnuradio#4335.

The current GR version is 3.8. After I'm done with the GRC version of gr_ais, I'll migrate the package to GR 3.9 moving forward.

**Comment by Pomme2Pin** [comment]
hello we are in the futur and we have a similar problem just like you we wants to install gr-ais for gnuradui but its not working at the and of the installation we have 
![image_2025-01-03_143323928](https://github.com/user-attachments/assets/d46c0e5f-a9d5-4e80-a32f-afc0c6843c2c)
and we also have this probnleme:
![image](https://github.com/user-attachments/assets/769d7618-b799-4337-b725-700ac5f2d6c3)
we are beginner in this 
Please help us if you are still alive in 2025 ;)
