### ISSUE TITLE
Doesn't build against Gnu Radio 3.7.6

### ISSUE THREAD

**Issue by krbaker** [bistromath/gr-ais#13]
Seems Gnu Radio likes changing things frequently :-(
CMake Error at CMakeLists.txt:114 (find_package):
  Could not find a configuration file for package "Gnuradio" that is
  compatible with requested version "3.7.6".

  The following configuration files were considered but not accepted:

    /usr/lib/arm-linux-gnueabihf/cmake/gnuradio/GnuradioConfig.cmake, version: 3.7.2.1

**Comment by mranostay** [comment]
@krbaker  What was the solution to this?
