### ISSUE TITLE
Cannot build on OS X - volk issue?

### ISSUE THREAD

**Issue by theforcedk** [bistromath/gr-ais#14]
Alderaan:~/Development/Radio/gnuradio/gr-ais/build make
[  4%] Linking CXX shared library libgnuradio-ais.dylib
Undefined symbols for architecture x86_64:
  "_volk_32fc_magnitude_squared_32f", referenced from:
      gr::ais::corr_est_cc_impl::work(int, std::__1::vector<void const*, std::__1::allocator<void const*> >&, std::__1::vector<void*, std::__1::allocator<void*> >&) in corr_est_cc_impl.cc.o
  "_volk_free", referenced from:
      gr::ais::corr_est_cc_impl::~corr_est_cc_impl() in corr_est_cc_impl.cc.o
  "_volk_get_alignment", referenced from:
      gr::ais::corr_est_cc_impl::corr_est_cc_impl(std::__1::vectorstd::__1::complex<float, std::__1::allocatorstd::__1::complex<float > > const&, float, unsigned int, float) in corr_est_cc_impl.cc.o
      gr::ais::corr_est_cc_impl::corr_est_cc_impl(std::__1::vectorstd::__1::complex<float, std::__1::allocatorstd::__1::complex<float > > const&, float, unsigned int, float) in corr_est_cc_impl.cc.o
  "_volk_malloc", referenced from:
      gr::ais::corr_est_cc_impl::corr_est_cc_impl(std::__1::vectorstd::__1::complex<float, std::__1::allocatorstd::__1::complex<float > > const&, float, unsigned int, float) in corr_est_cc_impl.cc.o
      gr::ais::corr_est_cc_impl::corr_est_cc_impl(std::__1::vectorstd::__1::complex<float, std::__1::allocatorstd::__1::complex<float > > const&, float, unsigned int, float) in corr_est_cc_impl.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [lib/libgnuradio-ais.dylib] Error 1
make[1]: **\* [lib/CMakeFiles/gnuradio-ais.dir/all] Error 2
make: **\* [all] Error 2

**Comment by theforcedk** [comment]
Exporting "LDFLAGS=-Wl,-undefined,dynamic_lookup cmake .." works.. no clue as to why.

**Comment by cn0xroot** [comment]
@theforcedk 

sudo port search gr-ais
Password:
Warning: port definitions are more than two weeks old, consider updating them by running 'port selfupdate'.
gr-ais @20151220 (science, comms)
    Provides augmented functionality (blocks, GRC definitions, apps, etc) for GNU Radio.
