### ISSUE TITLE
Block digital_msk_correlate_cc missing?

### ISSUE THREAD

**Issue by EdFuentetaja** [bistromath/gr-ais#15]
My GNU Radio Companion complains that this module is missing when opening ais.grc. Cannot find it anywhere among the sources.

**Comment by nickwest238** [comment]
Were you ever able to find a fix for this issue?

**Comment by bistromath** [comment]
The current version of gr-ais does not include GRC blocks. I'm (slowly)
working on releasing a Gnuradio 3.9 version which is GRC-based.

**Comment by nickwest238** [comment]
Thanks for the quick response. Does that mean that only the python executable can be used for now?

**Comment by bistromath** [comment]
Correct.

**Comment by bistromath** [comment]
I've updated gr-ais (on the "grc" branch for now) to include GRC blocks and a GRC top-level application. Please note that it will only work with a version of Gnuradio which includes fixes to the MSK timing error detector -- see gnuradio/gnuradio#4335.
