### ISSUE TITLE
Boost required to compile ais

### ISSUE THREAD

**Issue by tomnick** [bistromath/gr-ais#20]
Hi, I am not able to compile, getting the following error:

`vnc@Plotter:~/gr-ais/build$ cmake ../
-- Build type not specified: defaulting to release.
CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1470 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:60 (find_package)

CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1470 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:60 (find_package)

-- Could NOT find Boost
CMake Error at CMakeLists.txt:63 (message):
  Boost required to compile ais

What am I doing wrong?`

**Comment by bistromath** [comment]
Do you have Gnuradio installed? If so, what version of Boost do you have
installed? And what flavor/version of Linux?

**Comment by tomnick** [comment]
Gnuradio 3.7.10 is installed!

`$ dpkg -s libboost-dev | grep 'Version'
dpkg-query: package 'libboost-dev' is not installed and no information is available
`
Working on an Orangepi PC, ARMBIAN 5.60 stable Debian GNU/Linux 9 (stretch) 4.14.70-sunxi
