### ISSUE TITLE
Cmake error while building to GR0.8

### ISSUE THREAD

**Issue by slangooo** [bistromath/gr-ais#23]
Hi, I'm trying to build this module like other OOT modules using:
mkdir build
cd build
cmake ..
make
sudo make install
sudo ldconfig

However, during the third step (cmake ..) I am receiving the following fatal error:
 Generating doxygen xml for ais_swig_doc docs
warning: Tag `SYMBOL_CACHE_SIZE' at line 289 of file `/usr/gr-ais/build/swig/ais_swig_doc_swig_docs/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `SHOW_DIRECTORIES' at line 477 of file `/usr/gr-ais/build/swig/ais_swig_doc_swig_docs/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `HTML_ALIGN_MEMBERS' at line 803 of file `/usr/gr-ais/build/swig/ais_swig_doc_swig_docs/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `USE_INLINE_TREES' at line 956 of file `/usr/gr-ais/build/swig/ais_swig_doc_swig_docs/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `XML_SCHEMA' at line 1149 of file `/usr/gr-ais/build/swig/ais_swig_doc_swig_docs/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `XML_DTD' at line 1155 of file `/usr/gr-ais/build/swig/ais_swig_doc_swig_docs/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: doxygen no longer ships with the FreeSans font.
You may want to clear or change DOT_FONTNAME.
Otherwise you run the risk that the wrong font is being used for dot generated graphs.
[ 52%] Generating python docstrings for ais_swig_doc
Traceback (most recent call last):
  File "/usr/gr-ais/docs/doxygen/swig_doc.py", line 33, in <module>
    from doxyxml import DoxyIndex, DoxyClass, DoxyFriend, DoxyFunction, DoxyFile, base
  File "/usr/gr-ais/docs/doxygen/doxyxml/__init__.py", line 67, in <module>
    from doxyindex import DoxyIndex, DoxyFunction, DoxyParam, DoxyClass, DoxyFile, DoxyNamespace, DoxyGroup, DoxyFriend, DoxyOther
ModuleNotFoundError: No module named 'doxyindex'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/gr-ais/docs/doxygen/swig_doc.py", line 35, in <module>
    from gnuradio.doxyxml import DoxyIndex, DoxyClass, DoxyFriend, DoxyFunction, DoxyFile, base
ModuleNotFoundError: No module named 'gnuradio'
swig/CMakeFiles/ais_swig_swig_doc.dir/build.make:60: recipe for target 'swig/ais_swig_doc.i' failed
make[2]: *** [swig/ais_swig_doc.i] Error 1
CMakeFiles/Makefile2:196: recipe for target 'swig/CMakeFiles/ais_swig_swig_doc.dir/all' failed
make[1]: *** [swig/CMakeFiles/ais_swig_swig_doc.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I'd appreciate any help, thanks.

**Comment by bistromath** [comment]
Try pulling the repo and trying to build again. Doxygen docs for this project seem ridiculous, so I removed them.

**Comment by slangooo** [comment]
Now I'm getting the following error:
CMake Error: File /home/slango/gr-ais/docs/doxygen/Doxyfile.swig_doc.in does not exist.
CMake Error at /usr/local/lib/cmake/gnuradio/GrSwig.cmake:58 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  /usr/local/lib/cmake/gnuradio/GrSwig.cmake:112 (GR_SWIG_MAKE_DOCS)
  swig/CMakeLists.txt:48 (GR_SWIG_MAKE)

**Comment by slangooo** [comment]
I commented line 45 in swig/CmakeLists and it worked. 
set(GR_SWIG_DOC_FILE ${CMAKE_CURRENT_BINARY_DIR}/ais_swig_doc.i)

**Comment by slangooo** [comment]
Also I had to comment line 8 in ais_swig.i:
#%include "ais_swig_doc.i"

**Comment by slangooo** [comment]
Now the blocks are not showing in grc.

**Comment by bistromath** [comment]
Blocks do not currently show in GRC. There is no GRC component to the existing AIS package. I'm working on a release which is mostly GRC-based for GR3.8.

**Comment by bistromath** [comment]
I've updated gr-ais (on the "grc" branch for now) to include GRC blocks and a GRC top-level application. Please note that it will only work with a version of Gnuradio which includes fixes to the MSK timing error detector -- see https://github.com/gnuradio/gnuradio/pull/4335.
