### ISSUE TITLE
Python naming conflict with libais

### ISSUE THREAD

**Issue by vtmmm** [bistromath/gr-ais#27]
The name of the Python module is simply "ais"; this conflicts with [libais](https://github.com/schwehr/libais), which can parse AIS messages using a Python wrapper.

I'd like to use both gr-ais and libais using GR3.8 and Python 3.8+, as they are complimentary, but am running into issues trying to import them both.

I'm currently reading up on the correct way to import Python modules by path and reading up on/trying to use the importlib API, but if someone has already solved this issue I'm all ears. I also wanted to bring it up in case refactoring this module to use a less generic name could make sense.

**Comment by bistromath** [comment]
I'm refactoring gr-ais for GR 3.9, and I'll try to figure out how to get
them to coexist. Unfortunately, Python has adopted the Highlander model of
package naming -- there can be only one.

**Comment by vtmmm** [comment]
Okay, good deal!

**Comment by bistromath** [comment]
Fixed in 78e441.
